language: php

# Use container-based infrastructure
sudo: false

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script: vendor/bin/codecept run unit --coverage --report --xml

after_success:
 - mkdir build
 - mkdir build/logs
 - cp tests/_log/coverage.xml build/logs/clover.xml
 - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
