language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer install --prefer-source

script: vendor/bin/codecept run unit

after_success:
  - vendor/bin/codecept run --coverage --report

branches:
  only:
    - master
